# Generated by Django 6.0 on 2025-12-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
