# Generated by Django 6.0 on 2026-01-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_mail', '0002_contact_phone'),
        ('training', '0005_alter_course_discount_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.course'),
        ),
    ]
