# Generated by Django 5.2.8 on 2025-11-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('hero_image', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('tools', models.TextField(blank=True, default='[]')),
                ('course_duration', models.CharField(max_length=100)),
                ('course_breakdown', models.CharField(max_length=255)),
                ('course_modes', models.TextField(blank=True, default='[]')),
                ('why_choose', models.JSONField(blank=True, default=list)),
                ('core_modules', models.JSONField(blank=True, default=list)),
                ('career_opportunities', models.TextField(blank=True, default='[]')),
                ('course_highlights', models.TextField(blank=True, default='[]')),
                ('ideal_for', models.TextField(blank=True, default='[]')),
                ('curriculum', models.JSONField(blank=True, default=list)),
                ('images', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
