# Generated by Django 6.0 on 2025-12-21 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_breakdown',
            new_name='breakdown',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='career_opportunities',
        ),
        migrations.RemoveField(
            model_name='course',
            name='core_modules',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_highlights',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_modes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ideal_for',
        ),
        migrations.RemoveField(
            model_name='course',
            name='images',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='course',
            name='why_choose',
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='training.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='IdealFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_for', to='training.course')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose', to='training.course')),
            ],
        ),
    ]
