# Generated by Django 6.0 on 2025-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_coursefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
