# Generated by Django 6.0 on 2025-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_course_discount_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
