# Generated by Django 6.0 on 2025-12-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Software Engineer at Google' or 'Student'", max_length=100)),
                ('review', models.TextField(blank=True, help_text='Main testimonial text')),
                ('tag_text', models.CharField(blank=True, help_text="Short tag like 'Success' or 'Great Support'", max_length=50)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
